name: Deploy to GCP VM

on:
  push:
    branches:
      - main  # 푸시 이벤트 발생 시 자동 실행될 브랜치 이름 (main)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to VM via SSH
        run: |
          gcloud compute ssh keon-018 --zone "asia-northeast3-b" --project "${{ secrets.GCP_PROJECT_ID }}" --command "sudo git -C /var/www/html pull origin main && sudo systemctl restart httpd"